<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>PopreceiptSample</RootNamespace>
    <AssemblyName>PopreceiptSample</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Azure.Data.Tables" Version="12.12.0" />
    <PackageReference Include="Azure.Storage.Blobs" Version="12.29.2" />
    <PackageReference Include="Azure.Storage.Queues" Version="12.27.1" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.12" />
    <PackageReference Include="Azure.AI.Vision.Face" Version="1.0.0-beta.2" />
  </ItemGroup>

</Project>
